### ISSUE TITLE
作者您好！请问这个中文命名实体识别的方法是否由对应的论文，谢谢！

### ISSUE THREAD

**Issue by suifeng1227** [FadedCosine/Syntax-guided-Chinese-NER#1]

**Comment by FadedCosine** [comment]
这是我们的一个大作业项目，目前没有对应的论文，不过项目中给出了baseline论文，您可以参考：https://github.com/CLUEbenchmark/CLUENER2020  。另外，我们项目中的主要思想来自于SG-Net：https://arxiv.org/abs/1908.05147
